accounts/urls.py
#!/bin/python3

"""
Accounts module - URLs
"""

from django.urls import path

from .api import ProfileAutocompleteSearch, ProfileListApi, RevertUserActiveStatus
from .views import (
    MyProfileDetail,
    MyProfileDetailExport,
    MyProfileUpdate,
    UserCreate,
    UserDelete,
    UserDetail,
    UserListView,
    UserPassword,
    UserUpdate,
    change_password,
)

# from django.contrib.auth.paths import views
app_name = "accounts"

urlpatterns = [
    path("create", UserCreate.as_view(), name="user_create"),
    path("<int:pk>/update", UserUpdate.as_view(), name="user_update"),
    path("<int:pk>/password", UserPassword.as_view(), name="user_password"),
    path("<int:pk>/delete", UserDelete.as_view(), name="user_delete"),
    path("<int:pk>/detail", UserDetail.as_view(), name="user_detail"),
    path("myprofile/change_password", change_password, name="change_password"),
    path("myprofile/detail", MyProfileDetail.as_view(), name="myprofile_detail"),
    path(
        "myprofile/detail/export",
        MyProfileDetailExport.as_view(),
        name="myprofile_detail_export",
    ),
    path(
        "api/v1/profile/search",
        ProfileAutocompleteSearch.as_view(),
        name="profile_search_api",
    ),
    path(
        "api/v1/profile/list",
        ProfileListApi.as_view(),
        name="profile_list_api",
    ),
    path(
        "api/v1/profile/<int:pk>/switch-active-status",
        RevertUserActiveStatus.as_view(),
        name="profile_revert_active_status_api",
    ),
    path("myprofile/update", MyProfileUpdate.as_view(), name="myprofile_update"),
    path("list", UserListView.as_view(), name="user_search"),
]

api/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (  # GeoJSONTiledPlaceData,
    ActiveUserAutocomplete,
    AllUserAutocomplete,
    AreasAutocomplete,
    MetaplaceAutocomplete,
    PlaceAutocomplete,
    StudyAutocomplete,
    TaxaAutocomplete,
    metaplaces_as_geojson,
    places_as_geojson,
    places_in_metaplace_as_geojson,
)

app_name = "general_api"

urlpatterns = [
    path("place.geojson", places_as_geojson, name="geodata_place"),
    path("metaplaces.geojson", metaplaces_as_geojson, name="geodata_metaplaces"),
    path(
        "metaplaces/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_places_in_metaplaces",
    ),
    path(
        "metaplaces/<int:pk>/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_place_in_metaplace",
    ),
    # path(
    #     "place/<int:z>/<int:x>/<int:y>",
    #     GeoJSONTiledPlaceData.as_view(),
    #     name="placetiled",
    # ),
    path(
        "active-user-autocomplete/",
        ActiveUserAutocomplete.as_view(),
        name="active_user_autocomplete",
    ),
    path(
        "all-user-autocomplete/",
        AllUserAutocomplete.as_view(),
        name="all_user_autocomplete",
    ),
    path("taxa-autocomplete/", TaxaAutocomplete.as_view(), name="taxa_autocomplete"),
    path(
        "areas-autocomplete/",
        AreasAutocomplete.as_view(),
        name="areas_autocomplete",
    ),
    path("place-autocomplete/", PlaceAutocomplete.as_view(), name="place_autocomplete"),
    path(
        "metaplace-autocomplete/",
        MetaplaceAutocomplete.as_view(),
        name="metaplace_autocomplete",
    ),
    path(
        "v1/study/search",
        StudyAutocomplete.as_view(),
        name="study_autocomplete",
    ),
]

blog/urls.py
from django.urls import path

from .views import ActuCreate, ActuDelete, ActuDetail, ActuList, ActuUpdate, Home

app_name = "blog"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("news/list", ActuList.as_view(), name="news_list"),
    path("news/<int:pk>/detail", ActuDetail.as_view(), name="news_detail"),
    path("news/add", ActuCreate.as_view(), name="news_create"),
    path("news/<int:pk>/update", ActuUpdate.as_view(), name="news_update"),
    path("news/<int:pk>/delete", ActuDelete.as_view(), name="news_delete"),
]

core/urls.py
from django.urls import path

from .views import SystemInformation, UnauthorizedModify, UnauthorizedView, version_api

app_name = "core"
urlpatterns = [
    # url d'erreurs
    path("unauthorizedmodify", UnauthorizedModify.as_view(), name="update_unauth"),
    path("unauthorizedview", UnauthorizedView.as_view(), name="view_unauth"),
    # Info systeme
    path("sysinfo", SystemInformation.as_view(), name="sysinfo"),
    path("version", version_api, name="version"),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib.auth.urls import views
from django.contrib.gis import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from dbchiro.settings import REGISTRATION_APPROVAL

admin.autodiscover()
admin.site.index_title = "Tables de données"
admin.site.site_header = "Interface de gestion"

schema_view = get_schema_view(
    openapi.Info(
        title="dbChiroWev API",
        default_version="v1",
        description="dbChiro API docs",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="AGPL v3"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

if REGISTRATION_APPROVAL:
    registration_include = "registration.backends.admin_approval.urls"
else:
    registration_include = "registration.backends.default.urls"

urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(
        "accounts/",
        include(registration_include),
        name="registration",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="dbgestion_doc"),
    path("captcha/", include("captcha.urls")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("exports.urls", namespace="exports")),
    path("", include("sights.urls", namespace="sights")),
    path("", include("management.urls", namespace="management")),
    path("", include("dicts.urls", namespace="dicts")),
    path("", include("geodata.urls", namespace="geodata")),
    # path("", include("metadata.urls", namespace="metadata")),
    path("synthesis/", include("synthesis.urls", namespace="synthesis")),
    path("api/", include("api.urls", namespace="api")),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

exports/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .api import ExportViewSet
from .views import ExportDetail, ExportList

app_name = "exports"
router = DefaultRouter()

router.register(r"api/v1/exports", ExportViewSet, basename="exports")

urlpatterns = router.urls
urlpatterns += [
    # url de recherches de localités
    path("exports/<int:pk>", ExportDetail.as_view(), name="export_detail"),
    path("exports/", ExportList.as_view(), name="export_list"),
]

templates/main/footer.html
<footer class="footer">
  <div class="container-fluid">
    <span class="text-muted">

      <div class="btn-group btn-group-xs dropup">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="fi-at-sign"></i> <span class="hidden-xs">dbChiro</span> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="https://dbchiro.org" role="button"><i class="fi-web" style="font-size:1em;"></i>
              dbchiro.org</a></li>
          <li>
            <script>
              //<!--
              // protected email script by Joe Maller
              // JavaScripts available at http://www.joemaller.com
              // this script is free to use and distribute
              // but please credit me and/or link to my site
              emailE = 'dbchiro.org'
              emailE = ('project' + '@' + emailE)
              document.write('<a href="mailto:' + emailE + '?subject=Contact depuis le site dbchiro[.org]' + '">' +
                '<i class="fi-mail" style="font-size:1em;"></i> Contactez nous' + '</a>')
              //-->

            </script>
          </li>
        </ul>
      </div><span class="hidden-xs"> est un projet libre</span> <a class="btn btn-warning btn-xs"
        href="https://www.gnu.org/licenses/agpl-3.0.fr.html" target="_blank "><span class="hidden-xs">GNU</span>
        AGPL</a>
      <span class="hidden-xs">, les codes
        sources
        sont disponibles sur</span>
      <div class="btn-group btn-group-xs dropup">
        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="fa fa-gitlab"></i> FramaGit <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="https://framagit.org/dbchiro/dbchiroweb" target="_blank ">dbChiro<sub>[web]</sub>
              source code</a></li>
          <li><a href="https://framagit.org/dbchiro/dbchiroqgis" target="_blank ">dbChiro<sub>[QGIS]</sub>
              source code</a></li>
        </ul>
      </div><span class="hidden-xs">. Les principales ressources utilisées sont</span>
      <div class="btn-group btn-group-xs dropup">
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="fa fa-code"></i> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="https://www.djangoproject.com/" target="_blank">Django</a></li>
          <li><a href="http://postgis.net/" target="_blank">PostgreSQL | PostGIS</a></li>
          <li><a href="https://getbootstrap.com/docs/3.3/" target="_blank">Bootstrap</a></li>
          <li><a href="http://leafletjs.com/" target="_blank">Leaflet.js</a></li>
        </ul>
        <span class="hidden-xs"> &nbsp;| Version :</span>
        <span class="label label-default">{{VERSION}}</span>
      </div>

      <!-- Single button -->
    </span>
  </div>
</footer>

templates/main/head_leaflet.html
{% load leaflet_tags %}
{# CSS et JS de LeafLet #}
{% leaflet_js plugins="ALL" %}
{% leaflet_css  plugins="ALL"%}
<script>
  const mapTileLayers = JSON.parse("{{MAP_TILES|escapejs}}");
  const defaultCenter = JSON.parse("{{DEFAULT_CENTER|escapejs}}");
  const periods = JSON.parse("{{PERIODS|escapejs}}");
  const placeBaseUrl = "{% url 'sights:place_geosearch_api' %}";
  const sessionBaseUrl = "{% url 'sights:session_api' %}"
  const observationBaseUrl = "{% url 'sights:sighting_search_api' %}"
  const metaplaceBaseUrl = "{% url 'sights:metaplace_geosearch_api' %}";
  const specieDistributionUrl = "{% url 'synthesis:specie_distribution_api' %}";
  const countdetailExportUrl = "{% url 'sights:countdetail_export' %}";
  const studyListUrl = "{% url 'management:api_study_list' %}";

</script>

templates/main/head_main_assets.html
{% load static %}
<script>
  /*******************************************
   * Force reload page content when navigate *
   *******************************************/
  (function () {
    if (window.localStorage) {
      if (!localStorage.getItem('firstReLoad')) {
        localStorage['firstReLoad'] = true;
        window.location.reload();
      } else {
        localStorage.removeItem('firstReLoad');
      }
    }
  })();

</script>
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
<link rel="stylesheet" href="{% static 'css/font/source-sans-pro/source-sans-pro.css' %}" />
<link rel="stylesheet" href="{% static 'css/font/foundation-icons.css' %}" />
<link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/font/MapkeyIcons.css' %}" />
<link rel="stylesheet" href="{% static 'css/jquery/jquery-ui.theme.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/jquery/jquery-ui.structure.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/jquery/jquery-ui.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/bs3_custom_theme/theme.css' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/vue-select.css' %}" />
<script src="{% static 'js/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" defer></script>
<script src="{% static 'js/vue.js' %}" defer></script>
<script src="{% static 'js/vee-validate.js' %}" defer></script>
<script src="{% static 'js/vue-select.js' %}" defer></script>
<script src="{% static 'js/axios.min.js' %}" defer></script>
<script src="{% static 'js/preload_app.js' %}" defer></script>
<script src="{% static 'js/datatables.min.js' %} " defer></script>
<script src="{% static 'js/moment.min.js' %} " defer></script>
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %} " defer></script>
<script src="{% static 'js/what-input.js' %} " defer></script>
<script src="{% static 'js/chart.min.js' %}" defer></script>
<script src="{% static 'js/vue-chartjs.min.js' %}" defer></script>
<script src="https://cdn.jsdelivr.net/npm/vuejs-auto-complete@0.9.0/dist/build.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
<script src="{% static 'js/app.js' %} " defer></script>
<script>
  const userId = parseInt('{{ user.id }}');

</script>
{% if form %} {{ form.media }} {% endif %}
<!-- filter tag is for django filter -->
{% if filter %}{{ filter.form.media }}{% endif %}
<link rel="stylesheet" href="{% static 'css/app.css' %}" />

templates/main/sidebar.html
{% load i18n %}
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <a href="/"><img src="{% static 'img/dbchiro_main_logo.svg' %}" loading="lazy">
        dbChiro<sub>[web]</sub></a>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-user-circle"></i>
        {% trans 'Mon compte' %}
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="{% url 'accounts:myprofile_detail' %}"><i class="far fa-fw fa-id-card"></i>
            {% trans 'Mon profil' %}</a>
        </li>
        <li>
          <a href="{% url 'accounts:myprofile_update' %}"><i class="fa fa-fw fa-user-edit"></i>
            {% trans 'Modifier Mon profil' %}</a>
        </li>
        <li>
          <a href="{% url 'accounts:change_password' %}"><i class="fa fa-fw fa-key"></i>
            {% trans 'Modifier mon mot de passe' %}</a>
        </li>
            <li><a href="{% url 'exports:export_list' %}"><i class="fa fa-fw fa-download"></i>
              {% trans 'Mes exports' %}</a></li>
      </ul>
    </li>
    {# Fin du menu du compte utilisateur #}

    {% if user.is_authenticated %} {# Début du menu des Observations #}
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-eye"></i>
        {% trans 'Observations' %} <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="{% url 'sights:metaplace_search' %}"><i class="fas fa-fw fa-draw-polygon"></i>
            {% trans 'Métasites' %}</a></li>
    </li>
    <li><a href="{% url 'sights:place_search' %}"><i class="fa fa-fw fa-map-marker-alt"></i><span
          class="hide-for-small-only">
          {% trans 'Localités' %}</span></a></li>
    </li>
    <li><a href="{% url 'sights:session_search' %}"><i class="far fa-fw fa-calendar-alt"></i><span
      class="hide-for-small-only">
      {% trans 'Sessions' %}</span></a></li>
</li>
    <li>
      <a href="{% url 'sights:sighting_search' %}"><i class="fa fa-fw fa-list"></i>
        {% trans 'Observations' %}</a>
    </li>
    <li><a href="{% url 'management:study_list' %}"><i class="far fa-fw fa-clipboard"></i>
      {% trans 'Etudes' %}</a></li>
  </ul>
  </li>
  {# Fin du menu des Observations #}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <i class="fa fa-fw fa-chart-pie" aria-hidden="true"></i> {% trans 'Synthèse' %} <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'synthesis:global_contrib' %}"><i class="fa fa-fw fa-chart-line" aria-hidden="true"></i>
          {% trans 'Statistiques générales' %}</a>
      </li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'synthesis:specie_distribution' %}"><i class="fa fa-fw fa-chart-line"
            aria-hidden="true"></i>
          {% trans 'Cartes de répartition' %}</a>
      </li>
      {% endif %}
    </ul>
  </li>
  {# Début du menu de gestion #}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-paperclip"></i>
      {% trans 'Gestion' %}<span class="caret"></span>
    </a>

    <ul class="dropdown-menu">
      {% if user.is_resp or user.access_all_data or user.edit_all_data or user.is_staff or user.is_superuser %}
      <li><a href="{% url 'accounts:user_search' %}"><i class="fa fa-fw fa-list-alt"></i>
          {% trans 'Observateurs' %}</a>
      </li>
      <li><a href="{% url 'blog:news_list' %}"><i class="fa fa-fw fa-plus"></i> {% trans 'Actualités' %}</a>
      </li>
      {% endif %}
      <li><a href="{% url 'management:transmitter_list' %}"><i class="fa fa-fw fa-podcast"></i>
          {% trans 'Marqueurs' %}</span></a>
      </li>
  </li>
  <li><a href="{% url 'management:catchauth_list' %}"><i class="fa fa-fw fa-list"></i>
      {% trans 'Textes réglementaires' %}</a>
  </li>
  </ul>
  </li>
  {# Fin du menu de gestion #}
  {% if user.is_authenticated %}
  <li>
    <a href="{% url 'auth_logout' %}">
      <i class="fa fa-fw fa-sign-out-alt" aria-hidden="true"></i> {% trans 'Se déconnecter' %}
      ({{ user.username }})
    </a>
  </li>
  {% endif %}
   {% if user.is_superuser %}
   <li><a href="{% url 'core:sysinfo' %}"><i class="fa fa-fw fa-info"></i> {% trans 'Informations système' %}
   </a></li>
  <li><a href="{% url 'admin:index' %}"><i class="fa fa-fw fa-cogs"></i> {% trans 'Administration du site' %}
    </a></li>
  {% endif %} {% else %}
  <li>
    <a href="{% url 'registration_register' %}"><i class="fa fa-fw fa-sign-in-alt" aria-hidden="true"
        alt="Mot de passe oublié"></i> {% trans "S'enregistrer ?" %}
    </a>
  </li>
  <li>
    <a href="{% url 'auth_login' %}" alt="Se connecter"><i class="fa fa-fw fa-sign-in-alt" aria-hidden="true"></i>
      {% trans 'Se connecter' %}</a>
  </li>
  <li>
    <a href="{% url 'auth_password_reset' %}" alt="{% trans "Reset it" %}">
      <i class="fa fa-fw fa-lock" aria-hidden="true" alt="Se connecter"></i> {% trans "Forgot your password?" %}
    </a>
  </li>

  {% endif %}
  </ul>
</nav>
<button type="button" class="sidebar-open-icon is-closed" data-toggle="offcanvas" title="Menu">
  <i class="fas fa-chevron-circle-right fa-2x ontop"></i>
</button>

templates/main/topbar.html
{% load static i18n %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img alt="logo" height="30px" src="/media/logo_site.png" loading="lazy" />

      </a>
      <span class="navbar-text">{{SITE_NAME}}</span>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="#" class="navbar-link" data-toggle="modal" data-target="#searchPlace">
            <i class="fas fa-search-location"></i> {% trans 'Recherche rapide' %}
          </a></li>
        <li><a class="navbar-link" href="{% url 'accounts:myprofile_detail' %}" title="{% trans 'Mon profil' %}"><i
              class="fa fa-user-circle"></i>
            {{ user.get_username }}</a></li>
        <li><a class="navbar-link" href="{% url 'auth_logout' %}" title="{% trans 'Se déconnecter' %}"><i
              class="fa fa-fw fa-sign-out-alt" aria-hidden="true"></i> {% trans 'Se déconnecter' %}
          </a></li>
        {% else %}
        <li><a class="navbar-link" href="{% url 'auth_login' %}" title="{% trans 'Se connecter' %}"><i
              class="fa fa-fw fa-sign-in-alt" aria-hidden="true"></i> {% trans 'Se connecter' %}
          </a></li>
        {% endif %}
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>
{% if user.is_authenticated %}
<div id="searchPlace" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="fas fa-fw fa-search-location"></i>{% trans 'Rechercher rapidement une localité' %}
        </h4>
      </div>
      <div class="modal-body">
        <form id="TopBarPlaceSearch">
          <div class="form-group">
            <header-place-select type="text" class="form-control" placeholder="Search" v-model="id_place">
            </header-place-select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">{% trans 'Fermer' %}</button>
      </div>
    </div>
  </div>
</div>
{% endif %}