accounts/urls.py
#!/bin/python3

"""
Accounts module - URLs
"""

from django.urls import path

from .api import ProfileAutocompleteSearch, ProfileListApi, RevertUserActiveStatus
from .views import (
    MyProfileDetail,
    MyProfileDetailExport,
    MyProfileUpdate,
    UserCreate,
    UserDelete,
    UserDetail,
    UserListView,
    UserPassword,
    UserUpdate,
    change_password,
)

# from django.contrib.auth.paths import views
app_name = "accounts"

urlpatterns = [
    path("create", UserCreate.as_view(), name="user_create"),
    path("<int:pk>/update", UserUpdate.as_view(), name="user_update"),
    path("<int:pk>/password", UserPassword.as_view(), name="user_password"),
    path("<int:pk>/delete", UserDelete.as_view(), name="user_delete"),
    path("<int:pk>/detail", UserDetail.as_view(), name="user_detail"),
    path("myprofile/change_password", change_password, name="change_password"),
    path("myprofile/detail", MyProfileDetail.as_view(), name="myprofile_detail"),
    path(
        "myprofile/detail/export",
        MyProfileDetailExport.as_view(),
        name="myprofile_detail_export",
    ),
    path(
        "api/v1/profile/search",
        ProfileAutocompleteSearch.as_view(),
        name="profile_search_api",
    ),
    path(
        "api/v1/profile/list",
        ProfileListApi.as_view(),
        name="profile_list_api",
    ),
    path(
        "api/v1/profile/<int:pk>/switch-active-status",
        RevertUserActiveStatus.as_view(),
        name="profile_revert_active_status_api",
    ),
    path("myprofile/update", MyProfileUpdate.as_view(), name="myprofile_update"),
    path("list", UserListView.as_view(), name="user_search"),
]

api/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (  # GeoJSONTiledPlaceData,
    ActiveUserAutocomplete,
    AllUserAutocomplete,
    AreasAutocomplete,
    MetaplaceAutocomplete,
    PlaceAutocomplete,
    StudyAutocomplete,
    TaxaAutocomplete,
    metaplaces_as_geojson,
    places_as_geojson,
    places_in_metaplace_as_geojson,
)

app_name = "general_api"

urlpatterns = [
    path("place.geojson", places_as_geojson, name="geodata_place"),
    path("metaplaces.geojson", metaplaces_as_geojson, name="geodata_metaplaces"),
    path(
        "metaplaces/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_places_in_metaplaces",
    ),
    path(
        "metaplaces/<int:pk>/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_place_in_metaplace",
    ),
    # path(
    #     "place/<int:z>/<int:x>/<int:y>",
    #     GeoJSONTiledPlaceData.as_view(),
    #     name="placetiled",
    # ),
    path(
        "active-user-autocomplete/",
        ActiveUserAutocomplete.as_view(),
        name="active_user_autocomplete",
    ),
    path(
        "all-user-autocomplete/",
        AllUserAutocomplete.as_view(),
        name="all_user_autocomplete",
    ),
    path("taxa-autocomplete/", TaxaAutocomplete.as_view(), name="taxa_autocomplete"),
    path(
        "areas-autocomplete/",
        AreasAutocomplete.as_view(),
        name="areas_autocomplete",
    ),
    path("place-autocomplete/", PlaceAutocomplete.as_view(), name="place_autocomplete"),
    path(
        "metaplace-autocomplete/",
        MetaplaceAutocomplete.as_view(),
        name="metaplace_autocomplete",
    ),
    path(
        "v1/study/search",
        StudyAutocomplete.as_view(),
        name="study_autocomplete",
    ),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib.auth.urls import views
from django.contrib.gis import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from dbchiro.settings import REGISTRATION_APPROVAL

admin.autodiscover()
admin.site.index_title = "Tables de données"
admin.site.site_header = "Interface de gestion"

schema_view = get_schema_view(
    openapi.Info(
        title="dbChiroWev API",
        default_version="v1",
        description="dbChiro API docs",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="AGPL v3"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

if REGISTRATION_APPROVAL:
    registration_include = "registration.backends.admin_approval.urls"
else:
    registration_include = "registration.backends.default.urls"

urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(
        "accounts/",
        include(registration_include),
        name="registration",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="dbgestion_doc"),
    path("captcha/", include("captcha.urls")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("exports.urls", namespace="exports")),
    path("", include("sights.urls", namespace="sights")),
    path("", include("management.urls", namespace="management")),
    path("", include("dicts.urls", namespace="dicts")),
    path("", include("geodata.urls", namespace="geodata")),
    # path("", include("metadata.urls", namespace="metadata")),
    path("synthesis/", include("synthesis.urls", namespace="synthesis")),
    path("api/", include("api.urls", namespace="api")),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sights/observation/urls.py
from django.urls import path

from .api import EditSighting, GeoJSONSighting
from .views import SightingDetail, SightingEditForm, SightingSearch

urlpatterns = [
    # Sighting relative URLS
    # path(
    #     "session/<int:pk>/sighting/add",
    #     SightingCreate.as_view(),
    #     name="sighting_create",
    # ),
    path("sighting/<int:pk>/detail", SightingDetail.as_view(), name="sighting_detail"),
    # path("sighting/<int:pk>/update", SightingUpdate.as_view(), name="sighting_update"),
    # path("sighting/<int:pk>/delete", SightingDelete.as_view(), name="sighting_delete"),
    path("api/v1/search", GeoJSONSighting.as_view(), name="sighting_search_api"),
    path(
        "session/<int:pk>/sighting/edit",
        SightingEditForm.as_view(),
        name="sighting_edit_form",
    ),
    path(
        "api/v1/session/<int:session>/observation/list",
        EditSighting.as_view({"get": "list"}),
        name="count_detail_api",
    ),
    path(
        "api/v1/session/<int:session>/observation/add",
        EditSighting.as_view({"post": "create"}),
        name="post_observation_api",
    ),
    path(
        "api/v1/observation/<int:pk>/update",
        EditSighting.as_view({"put": "update"}),
        name="put_observation_api",
    ),
    path(
        "api/v1/observation/<int:pk>/delete",
        EditSighting.as_view({"delete": "destroy"}),
        name="delete_observation_api",
    ),
    path("sighting/search", SightingSearch.as_view(), name="sighting_search"),
]

sights/place/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from sights.place.api import GeoJSONBBoxFilteredPlaces, PlacesSearchApi
from sights.place.views import (
    BridgeCreate,
    BridgeDelete,
    BridgeUpdate,
    BuildCreate,
    BuildDelete,
    BuildUpdate,
    CaveCreate,
    CaveDelete,
    CaveUpdate,
    PlaceCreate,
    PlaceDelete,
    PlaceDetail,
    PlaceList,
    PlaceManagementCreate,
    PlaceManagementDelete,
    PlaceManagementUpdate,
    PlaceUpdate,
    TreeCreate,
    TreeDelete,
    TreeDetail,
    TreeGiteCreate,
    TreeGiteDelete,
    TreeGiteUpdate,
    TreeUpdate,
)

# router = routers.DefaultRouter()
# router.register(r"search", GeoJSONPlaces, "place_search")

urlpatterns = [
    # url de recherches de localités
    path("place/search", PlaceList.as_view(), name="place_search"),
    # Place views
    path(
        "place/map",
        login_required(TemplateView.as_view(template_name="place_map.html")),
        name="place_map",
    ),
    path("place/add", PlaceCreate.as_view(), name="place_create"),
    path(
        "metaplace/<int:id_metaplace>/place/add",
        PlaceCreate.as_view(),
        name="metaplace_place_create",
    ),
    path("place/<int:pk>/detail", PlaceDetail.as_view(), name="place_detail"),
    path("place/<int:pk>/update", PlaceUpdate.as_view(), name="place_update"),
    path("place/<int:pk>/delete", PlaceDelete.as_view(), name="place_delete"),
    # Place management relative URLS
    path(
        "place/<int:pk>/management/add",
        PlaceManagementCreate.as_view(),
        name="management_create",
    ),
    path(
        "management/<int:pk>/update",
        PlaceManagementUpdate.as_view(),
        name="management_update",
    ),
    path(
        "management/<int:pk>/delete",
        PlaceManagementDelete.as_view(),
        name="management_delete",
    ),
    # Build views
    path("place/<int:pk>/build/add", BuildCreate.as_view(), name="build_create"),
    path("build/<int:pk>/update", BuildUpdate.as_view(), name="build_update"),
    path("build/<int:pk>/delete", BuildDelete.as_view(), name="build_delete"),
    # Tree views
    path("place/<int:pk>/tree/add", TreeCreate.as_view(), name="tree_create"),
    path("tree/<int:pk>/update", TreeUpdate.as_view(), name="tree_update"),
    path("tree/<int:pk>/delete", TreeDelete.as_view(), name="tree_delete"),
    path("tree/<int:pk>/detail", TreeDetail.as_view(), name="tree_detail"),
    # TreeGite views
    path("tree/<int:pk>/treegite/add", TreeGiteCreate.as_view(), name="treegite_create"),
    path("treegite/<int:pk>/update", TreeGiteUpdate.as_view(), name="treegite_update"),
    path("treegite/<int:pk>/delete", TreeGiteDelete.as_view(), name="treegite_delete"),
    # Cave views
    path("place/<int:pk>/cave/add", CaveCreate.as_view(), name="cave_create"),
    path("cave/<int:pk>/update", CaveUpdate.as_view(), name="cave_update"),
    path("cave/<int:pk>/delete", CaveDelete.as_view(), name="cave_delete"),
    # Bridge views
    path("place/<int:pk>/bridge/add", BridgeCreate.as_view(), name="bridge_create"),
    path("bridge/<int:pk>/update", BridgeUpdate.as_view(), name="bridge_update"),
    path("bridge/<int:pk>/delete", BridgeDelete.as_view(), name="bridge_delete"),
    path("api/v1/place/search", PlacesSearchApi.as_view(), name="place_search_api"),
    path(
        "api/v1/place/geosearch",
        GeoJSONBBoxFilteredPlaces.as_view(),
        name="place_geosearch_api",
    ),
]

sights/session/urls.py
from django.urls import path

from sights.session.views import (
    DeviceCreate,
    DeviceDelete,
    DeviceUpdate,
    SessionChangePlaceUpdate,
    SessionCreate,
    SessionDelete,
    SessionDetail,
    SessionLinkCreate,
    SessionLinkDelete,
    SessionLinkUpdate,
    SessionSearch,
    SessionUpdate,
)

from .api import SessionApi

urlpatterns = [
    # Session relative URLS
    path(
        "place/<int:pk>/session/add",
        SessionCreate.as_view(),
        name="session_create",
    ),
    path(
        "session/<int:pk>/detail",
        SessionDetail.as_view(),
        name="session_detail",
    ),
    path(
        "session/<int:pk>/update",
        SessionUpdate.as_view(),
        name="session_update",
    ),
    path(
        "session/<int:pk>/change_place",
        SessionChangePlaceUpdate.as_view(),
        name="sessionchangeplace_update",
    ),
    path(
        "session/<int:pk>/delete",
        SessionDelete.as_view(),
        name="session_delete",
    ),
    # Device relative URLS
    path(
        "session/<int:pk>/device/add",
        DeviceCreate.as_view(),
        name="device_create",
    ),
    path("device/<int:pk>/update", DeviceUpdate.as_view(), name="device_update"),
    path("device/<int:pk>/delete", DeviceDelete.as_view(), name="device_delete"),
    path(
        "session/<int:pk>/link/add",
        SessionLinkCreate.as_view(),
        name="sessionlink_create",
    ),
    path("sessionlink/<int:pk>/update", SessionLinkUpdate.as_view(), name="sessionlink_update"),
    path("sessionlink/<int:pk>/delete", SessionLinkDelete.as_view(), name="sessionlink_delete"),
    path("api/v1/sessions", SessionApi.as_view(), name="session_api"),
    path("session/search", SessionSearch.as_view(), name="session_search"),
]

synthesis/urls.py
from django.urls import path

from .areas.api import AreaSynthesisApi
from .areas.views import AreaView
from .contribs.views import GlobalContribView
from .species.api import SpecieDistribution
from .species.views import SpecieDistributionView

app_name = "synthesis"

urlpatterns = [
    # url de recherches de localités
    path("contrib", GlobalContribView.as_view(), name="global_contrib"),
    path("area/<int:pk>", AreaView.as_view(), name="area_synthesis"),
    path("api/v1/synthesis/area/<int:pk>", AreaSynthesisApi.as_view(), name="area_synthesis_api"),
    path("specie/distribution", SpecieDistributionView.as_view(), name="specie_distribution"),
    path(
        "api/v1/synthesis/specie/distribution",
        SpecieDistribution.as_view(),
        name="specie_distribution_api",
    ),
]

accounts/templates/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>Mise à jour du mot de passe</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
</form>
{% endblock %}

accounts/templates/my_profile.html
{% extends 'base.html' %} {% load i18n %} {% block title %}Mon profil ({{ object.username }}){%endblock %}
{% block content %}
<h1>
  <i class="fi-torsos-female-male"></i>
  {% trans "Mon profil / Mes données" %}
</h1>
<p class="text-muted">Compte créé le {{object.timestamp_create}}{% if object.timestamp_update %}, mis à jour le
  {{object.timestamp_update}}.{% endif %}
  <div class="panel panel-group panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span class="pull-right">
          <a class="text-info" href="{% url 'accounts:myprofile_update' %}" data-toggle="tooltip"
            data-placement="bottom" title="{% trans 'Modifier Mon profil' %}"><i class="fa fa-fw fa-user-edit"></i></a>
          <a class="text-warning" href="{% url 'accounts:change_password' %}" data-toggle="tooltip"
            data-placement="bottom" title="{% trans 'Modifier mon mot de passe' %}"><i class="fa fa-fw fa-lock"></i>
          </a>
          <a class="text-info" href="{% url 'accounts:myprofile_detail_export' %}" data-toggle="tooltip"
          data-placement="bottom" title="{% trans 'Exporter mes données personnelles' %}"><i class="fa fa-fw fa-download"></i>
          </a>
        </span>
        <i class="fa fa-fw fa-id-card"></i> {% trans 'Mon profil' %}
      </h4>
    </div>
    <div class="panel-body">
      {% if not object.gcu_accepted %}
      <div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i>
        <a class="text-info" href="{% url 'accounts:myprofile_update' %}" data-toggle="tooltip"
            data-placement="bottom" title="{% trans 'Modifier Mon profil' %}">Veuillez accepter les conditions générales t'utilisations</a>
      </div>
      {% endif %}
      <h3>Informations principales</h1>
        <dl class="dl-horizontal">
          <dt>Nom d'utilisateur</dt>
          <dd>{{ object.username }}</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt>Nom complet</dt>
          <dd>{{ object.first_name }} {{ object.last_name }}</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt>Email</dt>
          <dd>{{ object.email }}</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt>Organisme</dt>
          <dd>{{ object.organism|default:'?' }}</dd>
        </dl>
        <h3>Coordonnées</h3>
        <dl class="dl-horizontal">
          <dt>Téléphone fixe</dt>
          <dd>{{ object.home_phone|default:'?' }}</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt>Téléphone mobile</dt>
          <dd>{{ object.mobile_phone|default:'?' }}</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt>Adresse</dt>
          <dd>
            {% if object.addr_apt or object.addr_building %}{{ object.addr_appt }}
            {{ object.addr_building }}<br>{% endif %}
            {{ object.addr_street|default:'?' }}<br>
            {{ object.addr_city_code|default:'?'}} {{ object.addr_city|default:'?'}}<br>
            {{ object.addr_country|default:'?'}}
          </dd>
        </dl>
    </div>
  </div>
  <div class="panel panel-group panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <i class="fa fa-fw fa-id-card"></i> {% trans 'Mes données' %}
      </h4>
    </div>
    <div class="panel-body">
      <div class="col-xs-12 col-md-4">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'sights:place_search' %}?only_mine={{object.pk}}"><i
            class="fa fa-fw fa-map-marker-alt"></i>
          {% trans 'Mes localités' %}</a>
      </div>
      <div class="col-xs-12 col-md-4">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'sights:session_search' %}?only_mine={{object.pk}}""><i
            class="fa fa-fw fa-calendar-alt"></i>
          {% trans 'Mes sessions' %}</a>
      </div>
      <div class="col-xs-12 col-md-4">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'sights:sighting_search' %}?only_mine={{object.pk}}"><i
            class="fa fa-fw fa-eye"></i>
          {% trans 'Mes observations' %}</a>
      </div>
    </div>
  </div>
  {% if object.is_superuser or object.is_resp or object.edit_all_data or object.access_all_data %}
  <div class="panel panel-group panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <i class="fa fa-fw fa-unlock"></i> {% trans 'Droits sur la base' %}
      </h4>
    </div>
    <div class="panel-body">
      <b>Super-utilisateur</b> : {{ object.is_superuser|yesno:'Oui,Non,-' }}<br />
      <b>Responsable de territoire</b> :
      <ul>
        {% for a in object.resp_areas.all %}
        <li><span class="label label-info">{{a.area_type.name}}</span> <code>{{ a.code }}</code>
          {{a.name}} <a href="{% url 'synthesis:area_synthesis' a.pk %}" title="détails"><i
              class="fa fa-info-circle"></i></a></li>
        {% endfor %}
      </ul>
      <b>Accès à toutes les données</b>: {{ object.access_all_data |yesno:'Oui,Non,-'}}<br />
      <b>Edition de toutes les données</b>: {{ object.edit_all_data|yesno:'Oui,Non,-'}}<br />
    </div>
  </div>
  {% endif %}
  {% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %} {% load i18n %} {% block title %}{% trans "Utilisateur" %} {{object.username}}{%endblock %}
{% block content %}
<h1>
  <i class="fi-torsos-female-male"></i>
  {% trans "Utilisateur" %} {{object.username}}
</h1>
<p> <span class="text-muted">Compte créé le</span> {{object.timestamp_create}}
  {% if object.timestamp_update %}
  <span class="text-muted">, mis à jour le </span>{{object.timestamp_update}}<span class="text-muted">.</span>
  {% endif %}
  <span class="text-muted"> Dernière connexion le </span>{{object.last_login|default:"Jamais"}}<span
    class="text-muted">.</span></p>
<div class="panel panel-group panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <i class="fa fa-fw fa-id-card"></i> {% trans 'Identité' %}
    </h4>
  </div>
  <div class="panel-body">
    {% if not object.gcu_accepted %}
    <div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i> Les conditions générales d'utilisations
      n'ont pas encore été acceptées par cet utilisateur</div>
    {% endif %}
    <h3>Informations principales</h1>
      <dl class="dl-horizontal">
        <dt>Nom d'utilisateur</dt>
        <dd><span class="label label-primary" style="font-size:1.5rem;">{{ object.username }}</strong></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Nom complet</dt>
        <dd>{{ object.first_name }} {{ object.last_name }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Email</dt>
        <dd>{{ object.email }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Organisme</dt>
        <dd>{{ object.organism|default:'?' }}</dd>
      </dl>
      <h3>Coordonnées</h3>
      <dl class="dl-horizontal">
        <dt>Téléphone fixe</dt>
        <dd>{{ object.home_phone|default:'?' }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Téléphone mobile</dt>
        <dd>{{ object.mobile_phone|default:'?' }}</dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Adresse</dt>
        <dd>
          {% if object.addr_apt or object.addr_building %}{{ object.addr_appt }}
          {{ object.addr_building }}<br>{% endif %}
          {{ object.addr_street|default:'?' }}<br>
          {{ object.addr_city_code|default:'?'}} {{ object.addr_city|default:'?'}}<br>
          {{ object.addr_country|default:'?'}}
        </dd>
      </dl>

  </div>
</div>
<div class="panel panel-group panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <i class="fa fa-fw fa-id-card"></i> {% trans 'Gestion' %}
    </h4>
  </div>
  <div class="panel-body">
    <div class="col-xs-12 col-md-4">
      <a class="btn btn-block btn-primary btn-lg" href="{% url 'accounts:user_update' pk=object.pk  %}"><i
          class="fa fa-fw fa-edit"></i>
        {% trans 'Modifier' %}</a>
    </div>
    <div class="col-xs-12 col-md-4">
      <a class="btn btn-block btn-warning btn-lg" href="{% url 'accounts:user_password' pk=object.pk %}"><i
          class="fa fa-fw fa-lock"></i>
        {% trans 'Changer le mot de passe' %}</a>
    </div>
    <div class="col-xs-12 col-md-4">
      <a class="btn btn-block btn-danger btn-lg" href="{% url 'accounts:user_delete' pk=object.pk %}"><i
          class="fa fa-fw fa-trash"></i>
        {% trans 'Supprimer' %}</a>
    </div>
  </div>
</div>
<div class="panel panel-group panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <i class="fa fa-fw fa-unlock"></i> {% trans 'Droits sur la base' %}
    </h4>
  </div>
  <div class="panel-body">
    <b>Super-utilisateur</b> : {{ object.is_superuser|yesno:'Oui,Non,-' }}<br />
    <b>Responsable de territoires</b> :
    <ul class="list-unstyled">
      {% for a in object.resp_areas.all %}
      <li><span class="label label-info">{{a.area_type.name}}</span> <code>{{ a.code }}</code>
        {{a.name}} <a href="{% url 'synthesis:area_synthesis' a.pk %}" title="détails"><i
            class="fa fa-info-circle"></i></a></li>
      {% endfor %}
    </ul>
    <b>Accès à toutes les données</b>: {{ object.is_superuser|yesno:'Oui,Non,-'}}<br />
    <b>Edition de toutes les données</b>: {{ object.edit_all_data|yesno:'Oui,Non,-'}}<br />
  </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        name: {{ field.name }}
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <a class="button" type="submit">Sign up</a>
  </form>
{% endblock %}