accounts/urls.py
#!/bin/python3

"""
Accounts module - URLs
"""

from django.urls import path

from .api import ProfileAutocompleteSearch, ProfileListApi, RevertUserActiveStatus
from .views import (
    MyProfileDetail,
    MyProfileDetailExport,
    MyProfileUpdate,
    UserCreate,
    UserDelete,
    UserDetail,
    UserListView,
    UserPassword,
    UserUpdate,
    change_password,
)

# from django.contrib.auth.paths import views
app_name = "accounts"

urlpatterns = [
    path("create", UserCreate.as_view(), name="user_create"),
    path("<int:pk>/update", UserUpdate.as_view(), name="user_update"),
    path("<int:pk>/password", UserPassword.as_view(), name="user_password"),
    path("<int:pk>/delete", UserDelete.as_view(), name="user_delete"),
    path("<int:pk>/detail", UserDetail.as_view(), name="user_detail"),
    path("myprofile/change_password", change_password, name="change_password"),
    path("myprofile/detail", MyProfileDetail.as_view(), name="myprofile_detail"),
    path(
        "myprofile/detail/export",
        MyProfileDetailExport.as_view(),
        name="myprofile_detail_export",
    ),
    path(
        "api/v1/profile/search",
        ProfileAutocompleteSearch.as_view(),
        name="profile_search_api",
    ),
    path(
        "api/v1/profile/list",
        ProfileListApi.as_view(),
        name="profile_list_api",
    ),
    path(
        "api/v1/profile/<int:pk>/switch-active-status",
        RevertUserActiveStatus.as_view(),
        name="profile_revert_active_status_api",
    ),
    path("myprofile/update", MyProfileUpdate.as_view(), name="myprofile_update"),
    path("list", UserListView.as_view(), name="user_search"),
]

api/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (  # GeoJSONTiledPlaceData,
    ActiveUserAutocomplete,
    AllUserAutocomplete,
    AreasAutocomplete,
    MetaplaceAutocomplete,
    PlaceAutocomplete,
    StudyAutocomplete,
    TaxaAutocomplete,
    metaplaces_as_geojson,
    places_as_geojson,
    places_in_metaplace_as_geojson,
)

app_name = "general_api"

urlpatterns = [
    path("place.geojson", places_as_geojson, name="geodata_place"),
    path("metaplaces.geojson", metaplaces_as_geojson, name="geodata_metaplaces"),
    path(
        "metaplaces/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_places_in_metaplaces",
    ),
    path(
        "metaplaces/<int:pk>/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_place_in_metaplace",
    ),
    # path(
    #     "place/<int:z>/<int:x>/<int:y>",
    #     GeoJSONTiledPlaceData.as_view(),
    #     name="placetiled",
    # ),
    path(
        "active-user-autocomplete/",
        ActiveUserAutocomplete.as_view(),
        name="active_user_autocomplete",
    ),
    path(
        "all-user-autocomplete/",
        AllUserAutocomplete.as_view(),
        name="all_user_autocomplete",
    ),
    path("taxa-autocomplete/", TaxaAutocomplete.as_view(), name="taxa_autocomplete"),
    path(
        "areas-autocomplete/",
        AreasAutocomplete.as_view(),
        name="areas_autocomplete",
    ),
    path("place-autocomplete/", PlaceAutocomplete.as_view(), name="place_autocomplete"),
    path(
        "metaplace-autocomplete/",
        MetaplaceAutocomplete.as_view(),
        name="metaplace_autocomplete",
    ),
    path(
        "v1/study/search",
        StudyAutocomplete.as_view(),
        name="study_autocomplete",
    ),
]

blog/urls.py
from django.urls import path

from .views import ActuCreate, ActuDelete, ActuDetail, ActuList, ActuUpdate, Home

app_name = "blog"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("news/list", ActuList.as_view(), name="news_list"),
    path("news/<int:pk>/detail", ActuDetail.as_view(), name="news_detail"),
    path("news/add", ActuCreate.as_view(), name="news_create"),
    path("news/<int:pk>/update", ActuUpdate.as_view(), name="news_update"),
    path("news/<int:pk>/delete", ActuDelete.as_view(), name="news_delete"),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib.auth.urls import views
from django.contrib.gis import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from dbchiro.settings import REGISTRATION_APPROVAL

admin.autodiscover()
admin.site.index_title = "Tables de données"
admin.site.site_header = "Interface de gestion"

schema_view = get_schema_view(
    openapi.Info(
        title="dbChiroWev API",
        default_version="v1",
        description="dbChiro API docs",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="AGPL v3"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

if REGISTRATION_APPROVAL:
    registration_include = "registration.backends.admin_approval.urls"
else:
    registration_include = "registration.backends.default.urls"

urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(
        "accounts/",
        include(registration_include),
        name="registration",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="dbgestion_doc"),
    path("captcha/", include("captcha.urls")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("exports.urls", namespace="exports")),
    path("", include("sights.urls", namespace="sights")),
    path("", include("management.urls", namespace="management")),
    path("", include("dicts.urls", namespace="dicts")),
    path("", include("geodata.urls", namespace="geodata")),
    # path("", include("metadata.urls", namespace="metadata")),
    path("synthesis/", include("synthesis.urls", namespace="synthesis")),
    path("api/", include("api.urls", namespace="api")),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

exports/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .api import ExportViewSet
from .views import ExportDetail, ExportList

app_name = "exports"
router = DefaultRouter()

router.register(r"api/v1/exports", ExportViewSet, basename="exports")

urlpatterns = router.urls
urlpatterns += [
    # url de recherches de localités
    path("exports/<int:pk>", ExportDetail.as_view(), name="export_detail"),
    path("exports/", ExportList.as_view(), name="export_list"),
]

synthesis/urls.py
from django.urls import path

from .areas.api import AreaSynthesisApi
from .areas.views import AreaView
from .contribs.views import GlobalContribView
from .species.api import SpecieDistribution
from .species.views import SpecieDistributionView

app_name = "synthesis"

urlpatterns = [
    # url de recherches de localités
    path("contrib", GlobalContribView.as_view(), name="global_contrib"),
    path("area/<int:pk>", AreaView.as_view(), name="area_synthesis"),
    path("api/v1/synthesis/area/<int:pk>", AreaSynthesisApi.as_view(), name="area_synthesis_api"),
    path("specie/distribution", SpecieDistributionView.as_view(), name="specie_distribution"),
    path(
        "api/v1/synthesis/specie/distribution",
        SpecieDistribution.as_view(),
        name="specie_distribution_api",
    ),
]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
  {% block meta %}{% endblock %}
  <!-- indiquez ici le titre de votre page -->
  <title>[{{ SITE_NAME }}] {% block title %}{% endblock %}</title>
  {# Inclusion des CSS principaux #}
  {% include "main/head_leaflet.html"%}
  {% include "main/head_main_assets.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

  </style>
</head>

<body>
  <div id="wrapper">
    {% include "main/sidebar.html" %}
    {% block page_header%}
    {% include "main/topbar.html" %}
    {% endblock %}
    {% comment %} <div class="overlay"></div> {% endcomment %}
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <noscript>
            <div class="alert alert-danger" role="alert">
              <strong>{% trans 'Ce site nécessite que JavaScript
                                    soit activé' %}</strong>
            </div>
          </noscript>
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>
{# Inclusion du footer de base #}
{% include "main/footer.html" %}

</html>

templates/base_fullwidth.html
{% load static i18n %}
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <!-- indiquez ici le titre de votre page -->
  <title>[{{ SITE_NAME }}] {% block title %}{% endblock %}</title>
  {# Inclusion des CSS principaux #}
  {% include "main/head_leaflet.html"%}
  {% include "main/head_main_assets.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

  </style>
</head>

<body>
  <div id="wrapper">
    {% include "main/sidebar.html" %}
    {% block page_header%}
    {% include "main/topbar.html" %}
    {% endblock %}
    {% comment %} <div class="overlay"></div> {% endcomment %}
    <div class="container-fluid">
      {% comment %}<div class="row">
        <div class="col-lg-12"> {% endcomment %}
          <noscript>
            <div class="alert alert-danger" role="alert">
              <strong>{% trans 'Ce site nécessite que JavaScript
                                    soit activé' %}</strong>
            </div>
          </noscript>
          {% block content %} {% endblock %}
          {% comment %} </div>
      </div>{% endcomment %}
    </div>
  </div>
</body>
{# Inclusion du footer de base #}
{% include "main/footer.html" %}

</html>

templates/base_fullwidth_leaflet.html
{% load static i18n %}
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <!-- indiquez ici le titre de votre page -->
  <title>[{{ SITE_NAME }}] {% block title %}{% endblock %}</title>
  {# Inclusion des CSS principaux #}
  {% include "main/head_leaflet.html"%}
  {% include "main/head_main_assets.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

  </style>
</head>

<body>
  <div id="wrapper">
    {% include "main/sidebar.html" %}
    {% block page_header%}
    {% include "main/topbar.html" %}
    {% endblock %}
    {% comment %} <div class="overlay"></div> {% endcomment %}
    <div class="container-fluid">
      {% comment %}<div class="row">
        <div class="col-lg-12"> {% endcomment %}
          <noscript>
            <div class="alert alert-danger" role="alert">
              <strong>{% trans 'Ce site nécessite que JavaScript
                                    soit activé' %}</strong>
            </div>
          </noscript>
          {% block content %} {% endblock %}
          {% comment %} </div>
      </div>{% endcomment %}
    </div>

  </div>
</body>
{# Inclusion du footer de base #}
{% include "main/footer.html" %}

</html>

templates/base_leaflet.html
{% load static i18n %}
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <!-- indiquez ici le titre de votre page -->
  <title>[{{ SITE_NAME }}] {% block title %}{% endblock %}</title>
  {# Inclusion des CSS principaux #}
  {% include "main/head_leaflet.html"%}
  {% include "main/head_main_assets.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

  </style>
</head>

<body>
  <div id="wrapper">
    {% include "main/sidebar.html" %}
    {% block page_header%}
    {% include "main/topbar.html" %}
    {% endblock %}
    {% comment %} <div class="overlay"></div> {% endcomment %}
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <noscript>
            <div class="alert alert-danger" role="alert">
              <strong>{% trans 'Ce site nécessite que JavaScript
                                    soit activé' %}</strong>
            </div>
          </noscript>
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>
{# Inclusion du footer de base #}
{% include "main/footer.html" %}

</html>

templates/confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1><i class="{{ icon | safe }}"></i> {{ title|safe }}</h1>
    <form action="" method="post">{% csrf_token %}
        <div class="alert alert-danger"><b>{{ message_alert }} "{{ object }}"?</b></div>
        <button type="submit" class="btn btn-danger" value="Confirm">{% trans 'Confirmer' %}</button>
    </form>
{% endblock %}

templates/export_done.html
{% extends 'base.html' %}
{% block title %}Export Done{% endblock %}
{% block content %}
<h1><i class="fas fa-info-circle"></i> Export done</h1>
<div class="columns callout">
	<h2>Export done</h2>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} Accueil {% endblock %}
{% block content %}

<div class="row" style="text-align:center;font-size:2rem;">
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="statBlock">
      <i class="text-muted fas fa-map-marked-alt fa-2x"></i><br>
      <span class="statCount">{{ placescount }}</span><br>
      <span class="statDesc text-muted"> {{ placestext }}</span><br>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="statBlock">
      <i class="text-muted fas fa-calendar-check   fa-2x "></i><br>
      <span class="statCount">{{ sessionscount }}</span><br>
      <span class="statDesc text-muted"> {{ sessionstext }}</span><br>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="statBlock">
      <i class="text-muted fas fa-eye fa-2x"></i><br>
      <span class="statCount">{{ sightingscount }}</span><br>
      <span class="statDesc text-muted"> {{ sightingstext }}</span><br>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="statBlock">
      <i class="text-muted fas fa-users fa-2x"></i><br>
      <span class="statCount">{{ observerscount }}</span><br>
      <span class="statDesc text-muted"> {{ observerstext }}</span><br>
    </div>
  </div>
</div>
{% if user.is_authenticated %}

<div class="row" style="text-align:center;font-size:2rem;">
  <div class="col-xs-12 col-sm-4">
    <a href="{% url 'accounts:myprofile_detail' %}" class="btn btn-warning btn-lg  btn-block">
      <i class="fa fa-user"></i> Mon profil
    </a>
  </div>
  <div class="col-xs-12 col-sm-4">
    <a href="{% url 'sights:place_search' %}" class="btn btn-success btn-lg  btn-block">
      <i class="fa fa-map"></i> Saisir
    </a>
  </div>
  <div class="col-xs-12 col-sm-4">
    <a href="{% url 'exports:export_list' %}" class="btn btn-info btn-lg  btn-block">
      <i class="fa fa-download"></i>  {% trans 'Mes exports' %}
    </a>
  </div>
</div>
<div class="row" id="synthesisHomePage" style="text-align:center;font-size:2rem;">
  <div class="col-xs-12 col-md-4">
      <a class="btn btn-primary btn-block" href="{% url 'synthesis:global_contrib' %}"> Statistiques générales</a>
  </div>
  <div class="col-xs-12 col-md-4">
      <a class="btn btn-primary btn-block" href="{% url 'synthesis:specie_distribution' %}"> Carte de répartitions</a>
  </div>
  <div class="col-xs-12 col-md-4">
    <a href="#" class="btn btn-primary btn-block" data-toggle="modal" data-target="#homeAreaSearch">
      <i class="fas fa-search-location"></i> {% trans 'Zonages' %}
    </a>
  </div>
</div>
{% else %}
<div class="row" style="text-align:center;font-size:2rem;">
  <div class="col-xs-12">
    <a href="{% url 'auth_login' %}" class="btn btn-info btn-lg  btn-block" alt="{% trans 'Se connecter' %}"><i
        class="fa fa-fw fa-sign-in-alt" aria-hidden="true"></i>
      {% trans 'Se connecter' %}</a>
  </div>
</div>
{% endif %}
<h1>
  <i class="{{ icon | safe }}"></i> {{ title }}
</h1>
<div class="row">
  <div class="col-lg-12">
    {% for object in object_list %}
    <div class="panel panel-default panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title"><a href="{% url 'blog:news_detail' pk=object.id_actu %}"><i class="fi-align-left"></i>
            {{ object.title }}</a></h2>
      </div>
      <div class="panel-body">
        <p>
          <small>
            {% if user.is_resp or user.access_all_data or user.edit_all_data or user.is_staff or user.is_superuser %}
            <a href="{% url 'blog:news_update' pk=object.id_actu %}" class="btn btn-xs btn-primary"><i
                class="fa fa-fw fa-edit"></i></a> {% endif %}
            créé le <b>{{ object.timestamp_create }}</b>
            par <b>{{ object.created_by }}</b>
            {% if object.updated_by %}| mis à jour le {{ object.timestamp_update }} par
            {{ object.updated_by.full_name }}{% endif %}
          </small>
        </p>
        <div class="well well-sm">{{ object.briefdescr|safe }}</div>
        <p class="text-right"><a href="{% url 'blog:news_detail' pk=object.id_actu %}"
            class="btn btn-sm btn-primary">Lire la suite
            ...</a></p>
      </div>
    </div>
    {% empty %}
    <div class="well">
      <div class="columns callout">Aucune actualité pour le moment.</div>
    </div>
    {% endfor %}
    {% if is_paginated %}
    <div class="columns ">
      <a class="pull-right btn btn-success"
        href="{% url 'blog:news_list' %}">{% trans 'Voir toutes les actualités' %}</a>
    </div>
    {% endif %}
  </div>
  <div id="homeAreaSearch" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><i class="fas fa-fw fa-search-location"></i>{% trans 'Rechercher rapide une localité' %}
          </h4>
        </div>
        <div class="modal-body">
          <form id="areaSearch">

    <div class="form-group">
      <label class="control-label" for="Area">Zonage</label>
      <p class="help-block">limites administratives, espaces naturels, etc.</p>
      <dict-select :options="dicts.AreaType" v-model="area_type" placeholder="Type de zonage"/>
    </div>
    <div class="form-group">
      <area-select id="Area" class="form-control" v-model="id" :areatype='area_type' />
    </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">{% trans 'Fermer' %}</button>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(() => {
    const vm = new Vue(homeAreaSearch())
  })
</script>
{% endblock %}

templates/leaflet_form.html
{% extends 'base_leaflet.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<style>
  .legend {
    padding: 6px 8px;
    font: 14px "LatoRegular", "Helvetica Neue", Helvetica, Arial, sans-serif;
    background: white;
    background: rgba(255, 255, 255, 0.8);
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    border-radius: 5px;
    line-height: 24px;
    color: #555;
  }

  .zoomInfo {
    padding: 5px;
  }

  .legend span {
    position: relative;
    bottom: 3px;
  }

  .legend i {
    width: 16px;
    height: 16px;
    float: left;
    margin: 0 8px 0 0;
    opacity: 0.7;
    border-radius: 50%;
  }

</style>
<h1><i class="{{ icon }}"></i> {{ title }}</h1>
{% if messages %}
<div class="small callout alert">
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
</div>
{% endif %}
{% if error_message %}
<div class="small callout alert">
  <b>{{ error_message }}</b>
</div>
{% endif %}
{% if form.errors %}
<div class="small callout alert">
  <b>{{ form.errors }}</b>
</div>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% crispy form %}
</form>
<link rel="stylesheet" href="{% static 'css/select2-bootstrap.min.css' %}">
<script>
  $(document).ready(() => {
    leafletForm()
  })

</script>

<script type="text/javascript">
  {{js | safe}}
 // $.fn.select2.defaults.set("theme", "bootstrap");

</script>
<br />

{% endblock %}

templates/normal_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <h1><i class="{{ icon }}"></i> {{ title }}</h1>
    {% if messages or error_message or form.errors %}
        <div class="alert alert-danger" role="alert">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                {% for message in error_message %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                {% for message in form.errors %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.min.css' %}">
    <script type="text/javascript">
        {{ js | safe }};

        {#$.fn.select2.defaults.set("theme", "bootstrap");#}
    </script>
    <br/>
    {#    {{ form.media }}#}

{% endblock %}

templates/sysinfo.html
{% extends 'base.html' %}
{% block title %} Information système{% endblock %}
{% block content %}
<h1><i class="fa fa-fw fa-info"></i> Information système</h1>
<div class="">
	<table class="table table-striped table-hover">
		{% for k, v in sysinfo.items %}
			<th>
			<td><strong>{{ k }}</strong></td>
			<td>{{v}}</td>
			</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

templates/table.html
{% extends 'base_fullwidth.html' %}
{% load i18n static crispy_forms_tags django_tables2 %}
{% block content %}

    <h1><i class="{{ icon | safe }}"></i> {{ title | safe }}</h1>
    {% if filter %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="" method="get">
                {% crispy filter.form %}
            </form>
        </div>
    </div>
    {% endif %}
    {% if count %}
        <div class="panel panel-default">
            <div class="panel-body">
                {% if export %}
                    <div class="btn-group btn-group-xs pull-right">
                        <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false">
                            {% trans 'Exporter' %} <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% querystring '_export'='csv' %}"> download as csv</a></li>
                            <li><a href="{% querystring '_export'='ods' %}"> download as ods</a></li>
                            <li><a href="{% querystring '_export'='xls' %}"> download as xlsx</a></li>
                            <li><a href="{% querystring '_export'='xlsx' %}"> download as xls</a></li>
                        </ul>
                    </div>
                {% endif %}
                {{ counttitle }} : <b>{{ count }}</b>
            </div>
        </div>
    {% endif %}

    <div class="panel panel-default">
        {% render_table table %}
    </div>

    <script type="text/javascript">
        {{ js | safe }}
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
    {% if filter %}
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.min.css' %}">
    <script type="text/javascript">
        {{ js | safe }}
        $.fn.select2.defaults.set("theme", "bootstrap");
    </script>
    {% endif %}

{% endblock %}

templates/unauthorized.html
{% extends 'base.html' %} {% block content %}
<h1><i class="fa fa-fw fa-exclamation-triangle"></i> Accès non autorisé</h1>
<div class="alert alert-danger">
	<p>{{ message }}</p>
</div>
{% endblock %}