api/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (  # GeoJSONTiledPlaceData,
    ActiveUserAutocomplete,
    AllUserAutocomplete,
    AreasAutocomplete,
    MetaplaceAutocomplete,
    PlaceAutocomplete,
    StudyAutocomplete,
    TaxaAutocomplete,
    metaplaces_as_geojson,
    places_as_geojson,
    places_in_metaplace_as_geojson,
)

app_name = "general_api"

urlpatterns = [
    path("place.geojson", places_as_geojson, name="geodata_place"),
    path("metaplaces.geojson", metaplaces_as_geojson, name="geodata_metaplaces"),
    path(
        "metaplaces/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_places_in_metaplaces",
    ),
    path(
        "metaplaces/<int:pk>/places.geojson",
        places_in_metaplace_as_geojson,
        name="geodata_place_in_metaplace",
    ),
    # path(
    #     "place/<int:z>/<int:x>/<int:y>",
    #     GeoJSONTiledPlaceData.as_view(),
    #     name="placetiled",
    # ),
    path(
        "active-user-autocomplete/",
        ActiveUserAutocomplete.as_view(),
        name="active_user_autocomplete",
    ),
    path(
        "all-user-autocomplete/",
        AllUserAutocomplete.as_view(),
        name="all_user_autocomplete",
    ),
    path("taxa-autocomplete/", TaxaAutocomplete.as_view(), name="taxa_autocomplete"),
    path(
        "areas-autocomplete/",
        AreasAutocomplete.as_view(),
        name="areas_autocomplete",
    ),
    path("place-autocomplete/", PlaceAutocomplete.as_view(), name="place_autocomplete"),
    path(
        "metaplace-autocomplete/",
        MetaplaceAutocomplete.as_view(),
        name="metaplace_autocomplete",
    ),
    path(
        "v1/study/search",
        StudyAutocomplete.as_view(),
        name="study_autocomplete",
    ),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib.auth.urls import views
from django.contrib.gis import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from dbchiro.settings import REGISTRATION_APPROVAL

admin.autodiscover()
admin.site.index_title = "Tables de données"
admin.site.site_header = "Interface de gestion"

schema_view = get_schema_view(
    openapi.Info(
        title="dbChiroWev API",
        default_version="v1",
        description="dbChiro API docs",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="AGPL v3"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

if REGISTRATION_APPROVAL:
    registration_include = "registration.backends.admin_approval.urls"
else:
    registration_include = "registration.backends.default.urls"

urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(
        "accounts/",
        include(registration_include),
        name="registration",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="dbgestion_doc"),
    path("captcha/", include("captcha.urls")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("exports.urls", namespace="exports")),
    path("", include("sights.urls", namespace="sights")),
    path("", include("management.urls", namespace="management")),
    path("", include("dicts.urls", namespace="dicts")),
    path("", include("geodata.urls", namespace="geodata")),
    # path("", include("metadata.urls", namespace="metadata")),
    path("synthesis/", include("synthesis.urls", namespace="synthesis")),
    path("api/", include("api.urls", namespace="api")),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

management/urls.py
from django.urls import path

from .regulatory.views import CatchAuthCreate, CatchAuthDelete, CatchAuthList, CatchAuthUpdate
from .study.api import StudyDatasApi, StudyListApi
from .study.views import StudyCreate, StudyDelete, StudyDetail, StudyList, StudyUpdate
from .transmitter.api import TransmitterSearchApi
from .transmitter.views import (
    TransmitterCreate,
    TransmitterDelete,
    TransmitterList,
    TransmitterUpdate,
)

app_name = "management"

urlpatterns = [
    # Study relative URLS
    path("study/add", StudyCreate.as_view(), name="study_create"),
    path("study/<int:pk>/edit", StudyUpdate.as_view(), name="study_update"),
    path("study/<int:pk>/delete", StudyDelete.as_view(), name="study_delete"),
    path("study/list", StudyList.as_view(), name="study_list"),
    path("api/v1/study/list", StudyListApi.as_view(), name="api_study_list"),
    path("study/list/<int:page>", StudyList.as_view(), name="url_study_list"),
    path("study/<int:pk>/detail", StudyDetail.as_view(), name="url_study_detail"),
    # path(
    #     "api/v1/study/<int:pk>/observations",
    #     StudySightingsApi.as_view(),
    #     name="api_study_sightings",
    # ),
    path("api/v1/study/<int:pk>/datas", StudyDatasApi.as_view(), name="api_study_data"),
    # Transmitter relative URLS
    path("transmitter/add", TransmitterCreate.as_view(), name="transmitter_create"),
    path(
        "transmitter/<int:pk>/update",
        TransmitterUpdate.as_view(),
        name="transmitter_update",
    ),
    path(
        "transmitter/<int:pk>/delete",
        TransmitterDelete.as_view(),
        name="transmitter_delete",
    ),
    path("transmitter/list", TransmitterList.as_view(), name="transmitter_list"),
    path(
        "transmitter/list/<int:page>",
        TransmitterList.as_view(),
        name="url_transmitter_list",
    ),
    path(
        "api/v1/transmitter/search",
        TransmitterSearchApi.as_view(),
        name="transmitter_search_api",
    ),
    # CatchAuth relative URLS
    path("catchauth/add", CatchAuthCreate.as_view(), name="catchauth_create"),
    path("catchauth/<int:pk>/update", CatchAuthUpdate.as_view(), name="catchauth_update"),
    path("catchauth/<int:pk>/delete", CatchAuthDelete.as_view(), name="catchauth_delete"),
    path("catchauth/list", CatchAuthList.as_view(), name="catchauth_list"),
    path("catchauth/list/<int:page>", CatchAuthList.as_view(), name="url_catchauth_list"),
]

sights/metaplace/urls.py
from django.urls import path

from sights.metaplace.api import MetaplaceGeoListApi, MetaplaceListApi
from sights.metaplace.views import (
    MetaplaceCreate,
    MetaplaceDelete,
    MetaplaceDetail,
    MetaplaceList,
    MetaplaceUpdate,
)

urlpatterns = [
    path("metaplace/add", MetaplaceCreate.as_view(), name="metaplace_create"),
    path("metaplace/", MetaplaceList.as_view(), name="metaplace_search"),
    path("metaplace/<int:pk>/detail", MetaplaceDetail.as_view(), name="metaplace_detail"),
    path("metaplace/<int:pk>/update", MetaplaceUpdate.as_view(), name="metaplace_update"),
    path("metaplace/<int:pk>/delete", MetaplaceDelete.as_view(), name="metaplace_delete"),
    path(
        "api/v1/metaplace/geosearch",
        MetaplaceGeoListApi.as_view(),
        name="metaplace_geosearch_api",
    ),
    path(
        "api/v1/metaplace",
        MetaplaceListApi.as_view(),
        name="metaplace_search_api",
    ),
]

sights/place/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from sights.place.api import GeoJSONBBoxFilteredPlaces, PlacesSearchApi
from sights.place.views import (
    BridgeCreate,
    BridgeDelete,
    BridgeUpdate,
    BuildCreate,
    BuildDelete,
    BuildUpdate,
    CaveCreate,
    CaveDelete,
    CaveUpdate,
    PlaceCreate,
    PlaceDelete,
    PlaceDetail,
    PlaceList,
    PlaceManagementCreate,
    PlaceManagementDelete,
    PlaceManagementUpdate,
    PlaceUpdate,
    TreeCreate,
    TreeDelete,
    TreeDetail,
    TreeGiteCreate,
    TreeGiteDelete,
    TreeGiteUpdate,
    TreeUpdate,
)

# router = routers.DefaultRouter()
# router.register(r"search", GeoJSONPlaces, "place_search")

urlpatterns = [
    # url de recherches de localités
    path("place/search", PlaceList.as_view(), name="place_search"),
    # Place views
    path(
        "place/map",
        login_required(TemplateView.as_view(template_name="place_map.html")),
        name="place_map",
    ),
    path("place/add", PlaceCreate.as_view(), name="place_create"),
    path(
        "metaplace/<int:id_metaplace>/place/add",
        PlaceCreate.as_view(),
        name="metaplace_place_create",
    ),
    path("place/<int:pk>/detail", PlaceDetail.as_view(), name="place_detail"),
    path("place/<int:pk>/update", PlaceUpdate.as_view(), name="place_update"),
    path("place/<int:pk>/delete", PlaceDelete.as_view(), name="place_delete"),
    # Place management relative URLS
    path(
        "place/<int:pk>/management/add",
        PlaceManagementCreate.as_view(),
        name="management_create",
    ),
    path(
        "management/<int:pk>/update",
        PlaceManagementUpdate.as_view(),
        name="management_update",
    ),
    path(
        "management/<int:pk>/delete",
        PlaceManagementDelete.as_view(),
        name="management_delete",
    ),
    # Build views
    path("place/<int:pk>/build/add", BuildCreate.as_view(), name="build_create"),
    path("build/<int:pk>/update", BuildUpdate.as_view(), name="build_update"),
    path("build/<int:pk>/delete", BuildDelete.as_view(), name="build_delete"),
    # Tree views
    path("place/<int:pk>/tree/add", TreeCreate.as_view(), name="tree_create"),
    path("tree/<int:pk>/update", TreeUpdate.as_view(), name="tree_update"),
    path("tree/<int:pk>/delete", TreeDelete.as_view(), name="tree_delete"),
    path("tree/<int:pk>/detail", TreeDetail.as_view(), name="tree_detail"),
    # TreeGite views
    path("tree/<int:pk>/treegite/add", TreeGiteCreate.as_view(), name="treegite_create"),
    path("treegite/<int:pk>/update", TreeGiteUpdate.as_view(), name="treegite_update"),
    path("treegite/<int:pk>/delete", TreeGiteDelete.as_view(), name="treegite_delete"),
    # Cave views
    path("place/<int:pk>/cave/add", CaveCreate.as_view(), name="cave_create"),
    path("cave/<int:pk>/update", CaveUpdate.as_view(), name="cave_update"),
    path("cave/<int:pk>/delete", CaveDelete.as_view(), name="cave_delete"),
    # Bridge views
    path("place/<int:pk>/bridge/add", BridgeCreate.as_view(), name="bridge_create"),
    path("bridge/<int:pk>/update", BridgeUpdate.as_view(), name="bridge_update"),
    path("bridge/<int:pk>/delete", BridgeDelete.as_view(), name="bridge_delete"),
    path("api/v1/place/search", PlacesSearchApi.as_view(), name="place_search_api"),
    path(
        "api/v1/place/geosearch",
        GeoJSONBBoxFilteredPlaces.as_view(),
        name="place_geosearch_api",
    ),
]

sights/session/urls.py
from django.urls import path

from sights.session.views import (
    DeviceCreate,
    DeviceDelete,
    DeviceUpdate,
    SessionChangePlaceUpdate,
    SessionCreate,
    SessionDelete,
    SessionDetail,
    SessionLinkCreate,
    SessionLinkDelete,
    SessionLinkUpdate,
    SessionSearch,
    SessionUpdate,
)

from .api import SessionApi

urlpatterns = [
    # Session relative URLS
    path(
        "place/<int:pk>/session/add",
        SessionCreate.as_view(),
        name="session_create",
    ),
    path(
        "session/<int:pk>/detail",
        SessionDetail.as_view(),
        name="session_detail",
    ),
    path(
        "session/<int:pk>/update",
        SessionUpdate.as_view(),
        name="session_update",
    ),
    path(
        "session/<int:pk>/change_place",
        SessionChangePlaceUpdate.as_view(),
        name="sessionchangeplace_update",
    ),
    path(
        "session/<int:pk>/delete",
        SessionDelete.as_view(),
        name="session_delete",
    ),
    # Device relative URLS
    path(
        "session/<int:pk>/device/add",
        DeviceCreate.as_view(),
        name="device_create",
    ),
    path("device/<int:pk>/update", DeviceUpdate.as_view(), name="device_update"),
    path("device/<int:pk>/delete", DeviceDelete.as_view(), name="device_delete"),
    path(
        "session/<int:pk>/link/add",
        SessionLinkCreate.as_view(),
        name="sessionlink_create",
    ),
    path("sessionlink/<int:pk>/update", SessionLinkUpdate.as_view(), name="sessionlink_update"),
    path("sessionlink/<int:pk>/delete", SessionLinkDelete.as_view(), name="sessionlink_delete"),
    path("api/v1/sessions", SessionApi.as_view(), name="session_api"),
    path("session/search", SessionSearch.as_view(), name="session_search"),
]

sights/urls.py
from django.urls import include, path

from sights.countdetail import urls as countdetail_urls
from sights.metaplace import urls as metaplace_urls
from sights.observation import urls as observation_urls
from sights.observation.views import SightingMyList, SightingUserList
from sights.place import urls as place_urls
from sights.place.views import PlaceMyList
from sights.session import urls as session_urls
from sights.session.views import SessionMyList

app_name = "sights"

urlpatterns = [
    path("user/place/list", PlaceMyList.as_view(), name="place_mylist"),
    path("user/session/list", SessionMyList.as_view(), name="session_mylist"),
    path("user/sighting/list", SightingMyList.as_view(), name="sighting_mylist"),
    path(
        "user/<int:pk>/sighting/list",
        SightingUserList.as_view(),
        name="user_sighting_list",
    ),
    path("", include(metaplace_urls)),
    path("", include(place_urls)),
    path("", include(session_urls)),
    path("", include(observation_urls)),
    path("", include(countdetail_urls)),
]

synthesis/urls.py
from django.urls import path

from .areas.api import AreaSynthesisApi
from .areas.views import AreaView
from .contribs.views import GlobalContribView
from .species.api import SpecieDistribution
from .species.views import SpecieDistributionView

app_name = "synthesis"

urlpatterns = [
    # url de recherches de localités
    path("contrib", GlobalContribView.as_view(), name="global_contrib"),
    path("area/<int:pk>", AreaView.as_view(), name="area_synthesis"),
    path("api/v1/synthesis/area/<int:pk>", AreaSynthesisApi.as_view(), name="area_synthesis_api"),
    path("specie/distribution", SpecieDistributionView.as_view(), name="specie_distribution"),
    path(
        "api/v1/synthesis/specie/distribution",
        SpecieDistribution.as_view(),
        name="specie_distribution_api",
    ),
]

sights/templates/metaplace_detail.html
{% extends 'base_fullwidth_leaflet.html' %}
{% load leaflet_tags %}
{% leaflet_js plugins="ALL" %}
{% load geojson_tags %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% block content %}
<style>
  #mapContainer {
    height: 500px;
    min-height: 500px;
  }

</style>
<h1 xmlns="http://www.w3.org/1999/html"><i class="{{ icon | safe }}"></i> {{ title }}</h1>
<p>
  <small>Localité créée par <b>{{ object.created_by.full_name }}</b> le <b>{{ object.timestamp_create }}</b> et mise
    à jour le <b>{{ object.timestamp_update }}</b></small>
</p>
<div class="row">
  <div class="col-md-12 col-lg-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="pull-right btn-group">
          <a href="{% url 'sights:metaplace_update' pk=object.id_metaplace %}" class="btn btn-default btn-xs"><i
              class="fa fa-fw fa-edit"></i><span class="hidden-xs"> Modifier</span></a>
          <a href="{% url 'sights:metaplace_delete' pk=object.id_metaplace %}" class="btn btn-danger btn-xs"><i
              class="fa fa-fw fa-trash"></i><span class="hidden-xs"> Supprimer</span></a>
        </div>
        <h4 class="panel-title"><i class="fas fa-info-circle"></i> Informations sur la localité</h4>
      </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <fieldset>
              <legend>Caractéristiques principales</legend>
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <label>Nom du métasite</label>
                  <div class="well well-sm">{{ object.name }}</div>
                </div>
                <div class="col-xs-12 col-md-6">
                  <label>Type</label>
                  <div class="well well-sm">
                    {% if object.type %}
                    {{ object.type.descr }}{% else %}
                    -{% endif %}</div>
                </div>
            </fieldset>

            <fieldset>
              <legend>Localisation géographique</legend>
              <div class="row">
                <div class="col-lg-12">
                  <label>Zonages</label>
                  <div class="well well-sm">
                    {% for a in object.areas.all %}
                    <span class="label label-info">{{a.area_type.name}}</span> <code>{{ a.code }}</code>
                    {{a.name}} <a href="{% url 'synthesis:area_synthesis' a.pk %}" title="Modifier"><i
                        class="fa fa-info-circle"></i></a><br>
                    {% endfor %}
                  </div>
                </div>
                <div class="col-lg-12">
                  {% if object.autogeom %}
                  <p><i class="fas fa-draw-polygon"></i> Polygone généré selon les localités associées </p>
                  {% else %}
                  <i class="fas fa-draw-polygon"></i> Polygone dessiné manuellement
                  {% endif %}
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  {% comment %} {% leaflet_map "map" callback="window.map_init_basic" %} {% endcomment %}
                  <div id="mapContainer"></div>
                  <script type="text/javascript">
                    const metasite = JSON.parse('{{ object.geom | geojsonfeature | safe }}');
                    {% comment %} const placesUrl = '{% url "api:geodata_place_in_metaplace" pk=object.id_metaplace %}' {% endcomment %}
                    $(document).ready(() => {
                      metaplaceDetail(placeBaseUrl, parseInt('{{object.id_metaplace}}'))
                    })

                  </script>
                  <script type="text/javascript">
                    function map_init_basic(map, options) {

                    };

                  </script>
                </div>
              </div>
            </fieldset>

          </div>
        </div>
      </div>
    </div>
  </div>

  {% comment %}


  DONNEES ATTRIBUEES A LA LOCALITE


  {% endcomment %}
  <div class="col-md-12 col-lg-7">
    <div id="accordion" class="panel-group">
      {% comment %}

      BLOC1: Places d'inventaires

      {% endcomment %}
      <div class="panel panel-default panel-info panel-table">
        <!-- Default panel contents -->
        <div class="panel-heading">
          <div class="pull-right btn-group btn-group-xs">
            {% if placecount > 0 %}
            <a class="btn btn-default" data-toggle="collapse" data-parent="#accordion" href="#collapsePlace"
              title="voir/cacher la liste"><span class="caret"></span></a>
            {% endif %}
            <a href="{% url 'sights:metaplace_place_create' id_metaplace=object.id_metaplace %}"
              class="pull-right btn btn-primary btn-xs"><i class="fi-plus"></i> Nouvelle localité</a>
          </div>
          <h4><i class="{{ placeicon }}"></i> Places d'inventaires</a>
            <span class="badge">{{ Placecount }}</span>
          </h4>
        </div>

        <!-- Table -->
        {% if placecount > 0 %}
        <div id="collapsePlace" class="panel-body">
          {% render_table placetable %}
        </div>
        {% endif %}
      </div>

    </div>
  </div>
</div>

<br /> {% endblock %}

sights/templates/metaplace_search.html
{% extends 'base_fullwidth_leaflet.html' %}
{% load leaflet_tags i18n static crispy_forms_tags django_tables2 geojson_tags %}
{% leaflet_js %} {% leaflet_css %}
{% block jsvar %} {% endblock %}
{% block title %}{{ title | safe }}{% endblock %}
{% block content %}
<style>


</style>

<div id="ModelSearch">
  <h1>
    <span class="btn btn-group pull-right">
      <a href="{% url 'sights:metaplace_create' %}" class="btn btn-success"><i
          class="fa fa-fw fa-map-marker-alt"></i><strong>
          {% trans 'Créer un métasite' %}</strong></a>
    </span>
    <i class="{{ icon | safe }}"></i> {{ title | safe }}
  </h1>
  {% comment %}Tableau de recherche avec filtrage {% endcomment %}
  <div class="row">
    <div class="col col-xs-12 col-sm-4 col-md-3 col-lg-2">
      <div class="panel">
        <div class="panel-body searchBlock">
          <span class="label label-success pull-right">[[data.count ? data.count : 0]] résultats</span>
          <p class=" text-info"> <i class="fa fa-search fa-fw"></i>Rechercher</p>
          <form v-on:keyup.enter="search()">
            <div class="form-group form-group-sm">
              <label for="searchSearch">Nom</label>
              <input class="form-control" id="searchSearch" type="text" placeholder="Nom" v-model="filters.name">
            </div>
            <div class="form-group">
              <label class="control-label" for="Area">Zonage</label>
              <p class="help-block">limites administratives, espaces naturels, etc.</p>
              <dict-select :options="dicts.AreaType" v-model="area_type" placeholder="Type de zonage"/>
            </div>
            <div class="form-group">
              <area-select id="Area" class="form-control" v-model="filters.area" :areatype='area_type' />
            </div>
            {% comment %} <div class="form-group form-group-sm"> {% endcomment %}
              <div class="form-group" class="form-group">
                <label class="control-label" for="Precision">Type</label>
                <dict-select :options="dicts.MetaplaceType" v-model="filters.type" />
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" v-model="filters.created_by" :true-value="userId" :false-value="null"> Créé
                  par
                  moi
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" v-model="filters.updated_by" :true-value="userId" :false-value="null">
                  Modifié
                  par moi
                </label>
              </div>
              <input type="text" @click="search()" class="btn btn-block btn-primary btn-sm" value="Rechercher">
              {% comment %}
              <pre>[[filters]]</pre> {% endcomment %}
          </form>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 col-md-5 col-lg-5">
      <div id="dataTable" class="panel panel-default table-responsive tableFixHead">
        <table id="place_results" class="table  table-fixed table-striped table-condensed map-navigation"
          cellspacing="0" width="100%">
          <thead>
            <tr>
              <th style="width: 80px;">Actions</th>
              <th>Nom</th>
              <th>Type</th>
              <th>Localités</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="f in dataList.features" @click="feature=f">
              <td>
                <a :href="`/metaplace/${f.id}/detail`" class="text-primary"><i class="fa fa-info-circle"
                    title="Fiche détaillée" target="_blank"></i></a>
                <a :href="`/metaplace/${f.id}/update`" class="text-info"><i class="fa fa-edit" title="Editer"
                    target="_blank"></i></a>
                <a :href="`/metaplace/${f.id}/add/place`" class="text-info"><i class="fa fa-map-marker"
                    title="Créer une localité" target="_blank"></i></a>
                </a>
              </td>
              <td><a :href="`/metaplace/${f.id}/detail`" class="text-primary" tatget="_blank"
                  title="Fiche détaillée">[[f.properties.name]]</a></td>
              <td>[[f.properties.type ? f.properties.type.descr : '']]</td>
              <td>[[f.properties.count_places]]</td>
            </tr>
            <tr v-if="loading">
              <td class="text-center text-muted" colspan="6">
                Chargement en cours...
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {% if debug %}
      {% comment %}
      <pre>[[data.features?data.features.find(x=>true):'']]</pre> {% endcomment %}

      {%endif%}
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
      <place-map :feature="feature"></place-map>
    </div>
  </div>
</div>
<script>
  const dataUrl = "{% url 'sights:metaplace_geosearch_api' %}";

  $(document).ready(() => {
    const prefilledFilters = getQueryStrings();
    if ('{% if only_mine %}{{only_mine|yesno:"true,false"}}{% endif %}' === 'true') {
       prefilledFilters.onlyMine = true;
    };
    const vm = new Vue(ModelSearch(dataUrl, userId, prefilledFilters));
  })

</script>
{% endblock %}

sights/templates/place_map.html
{% extends 'base_fullwidth_leaflet.html' %}
{% load i18n leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
{% block title %}Carte des localités{% endblock %}
{% block content %}
<style>
  .legend {
    padding: 6px 8px;
    font: 14px "LatoRegular", "Helvetica Neue", Helvetica, Arial, sans-serif;
    background: white;
    background: rgba(255, 255, 255, 0.8);
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    border-radius: 5px;
    line-height: 24px;
    color: #555;
  }

  .legend span {
    position: relative;
    bottom: 3px;
  }

  #mapContainer {
    width: 100%;
    height: calc(100vh - 200px);
  }

</style>
<h1>
  <div class="btn btn-group pull-right">
    <a href="{% url 'sights:metaplace_create' %}" class="btn btn-success"><i
        class="fa fa-fw fa-map-marker-alt"></i><strong>
        {% trans 'Créer un métasite' %}</strong></a>
    <a href="{% url 'sights:place_create' %}" class="btn btn-success"><i class="fa fa-fw fa-map-marker-alt"></i><strong>
        {% trans 'Créer une localité' %}</strong></a>
  </div>
  <i class="fa fa-fw fa-map">

  </i> Carte des localités
</h1>
<p>Le groupement des localités est aléatoire, afin d'améliorer la vitesse d'affichage seulement.</p>
<div id="PlaceMap">
  <place-map></place-map>
</div>
<script>
  $(document).ready(() => {
    const vm = new Vue(PlaceMap());
  })

</script>
{% comment %} {% leaflet_map "main" %} {% endcomment %}

{% endblock %}